# Generated by Django 5.2.5 on 2025-08-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_company_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('passenger', 'Passenger'), ('company_admin', 'Company Admin')], default='passenger', max_length=20),
        ),
    ]
